version: "3.7"
services:
  caddy:
    image: skr32/custom-caddy2
    build: .
    container_name: caddy
    #ports:
    #  - 80:80
    #  - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy   
      - caddy_wan
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    restart: unless-stopped
    labels:
      caddy_0: ${WILDCARD_DOMAIN}
#"*.bagoize.com"
      caddy_0.tls.dns: cloudflare ${CLOUDFLARE_API_TOKEN}
      caddy_0.tls.resolvers: 1.1.1.1
      caddy_0.handle.abort:
      caddy_1: "(CF-IP)"
      caddy_1.header_up_0: "X-Forwarded-For {header.CF-Connecting-IP}"
      caddy_1.header_up_1: "X-Real-IP {header.CF-Connecting-IP}"

networks:
  caddy:
  caddy_wan:

volumes:
  caddy_data: {}
