      services:
        crowdsec:
          image: docker.io/crowdsecurity/crowdsec:latest
          container_name: crowdsec
          environment:
            - GID=1000
            - COLLECTIONS=crowdsecurity/caddy crowdsecurity/http-cve crowdsecurity/whitelist-good-actors
            - CUSTOM_HOSTNAME=myserver
          volumes:
            - /opt/appdata/crowdsec/config:/etc/crowdsec:rw
            - /opt/appdata/crowdsec/data:/var/lib/crowdsec/data:rw
            - /opt/appdata/swag/log/nginx:/var/log/swag:ro
            - /var/log:/var/log/host:ro      
          networks:
            - crowdsec
          restart: unless-stopped
          security_opt:
            - no-new-privileges=true

      networks:
        crowdsec:
          external: true