all:
  hosts:
    testvm:
      ansible_host: 10.98.1.183
      ansible_user: ansible
      ansible_ssh_private_key_file: ~/.ssh/id_rsa 

  children:
    debian_machines:
      hosts:
        testvm:

    docker:
      hosts:
        testvm:
